* general configuration

Make org-mode the defualt file mode
#+BEGIN_SRC emacs-lisp
  (setq-default major-mode 'org-mode)
#+END_SRC

This will remove any trailing whitespace on save
#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

Let the yank command access the last thing copied to the system
clipboard
#+BEGIN_SRC emacs-lisp
(setq select-enable-clipboard t
      select-enable-primary t
      save-interprogram-paste-before-kill t)
#+END_SRC

Let the apropos help search include non-interactive functions in its
search
#+BEGIN_SRC emacs-lisp
(setq apropos-do-all t)
#+END_SRC

Flash top and bottom bars of the screen as an alert
#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC

Set the maximum length of a string printed by evaluating a function to
unlimited
#+BEGIN_SRC emacs-lisp
(setq eval-expression-print-length nil)
#+END_SRC

Use ido-mode for finding files and buffers. Enabling flex matching
will make it a fuzzy search.
#+BEGIN_SRC emacs-lisp
  (ido-mode t)
  (setq ido-enable-flex-matching t)
#+END_SRC

Auto-saved files should be saved to '~/.emacs.d/auto-save/'. This
obviously requires this directory to be in place.
#+BEGIN_SRC emacs-lisp
  (setq auto-save-file-name-transforms
        `((".*" ,(concat user-emacs-directory "auto-save/") t)))
#+END_SRC

* text-mode configuration

Turn on auto-fill mode.
#+BEGIN_SRC emacs-lisp
(add-hook 'text-mode-hook 'turn-on-auto-fill)
#+END_SRC

* prog-mode configuration

prog mode is the super class of every programming language mode

require the linum-relative package which enables relative line numbers
#+BEGIN_SRC emacs-lisp
  (use-package linum-relative
               :ensure t)
#+END_SRC

Define and then set a function to start in prog-mode. The function
will:
- turn on relative line numbering
- require a final \n character at the end of the file
#+BEGIN_SRC emacs-lisp
  (defun my-prog-mode-config ()
    (linum-relative-on)
    (setq require-final-newline t))

  (add-hook 'prog-mode-hook 'my-prog-mode-config)
#+END_SRC
